CHUNK = 1024
DEFAULT_TIMEOUT = 1.0 # seconds

NUM_SEPARATOR = ','
RANGE_FMT = '%d' + NUM_SEPARATOR + '%d'

MSG_HELLO = 'HI'
MSG_PREPARE = 'PREPARE'
MSG_OK = 'OK'
MSG_COMPLETED = 'COMPLETED'
MSG_BYE = 'BYE'
